[package]
name = "rust-ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.13"
fixedbitset = "0.5.7"
glam = "0.29.2"
macros = { path = "macros" }
tracing = "0.1.41"
