[package]
name = "rust-ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.4.2"
glam = "0.24.2"
winit = "0.28.7"
macros = { path = "macros" }

