[package]
name = "rust-ecs-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ecs = { path = "../"}
macroquad = "0.4.13"
